name: Assemble

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      java-version:
        default: '17'
        required: false
        type: string
      java-distro:
        default: 'temurin'
        required: false
        type: string

jobs:
  assemble:
    name: 'Assemble ${{ matrix.job.os }}'
    strategy:
      fail-fast: false
      matrix:
        job: 
          - { os: ubuntu-latest,    platform: linux-x86_64,   platformReplaced: linux-x86_64   }
          - { os: ubuntu-22.04-arm, platform: linux-aarch_64, platformReplaced: linux-aarch64  }
          - { os: macos-13,         platform: osx-x86_64,     platformReplaced: osx-x86_64     }
          - { os: macos-14,         platform: osx-aarch_64,   platformReplaced: osx-aarch64    }
          - { os: windows-latest,   platform: windows-x86_64, platformReplaced: windows-x86_64 }
    runs-on: ${{ matrix.job.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distro }}
          cache: maven

      - name: Setup JDKs
        run: ./mvnw -ntp -B -q --file pom.xml -Pjdks
        
      - name: Build
        run: ./mvnw -ntp -B --file pom.xml verify

      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble --select-current-platform
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-assemble-${{ runner.os }}-${{ runner.arch }}
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Upload jpackage
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: artifacts-${{ runner.os }}-${{ runner.arch }}
          path: |
            out/jreleaser/assemble/jbang-launch/jpackage/*.pkg
            out/jreleaser/assemble/jbang-launch/jpackage/*.dmg
            out/jreleaser/assemble/jbang-launch/jpackage/*.deb
            out/jreleaser/assemble/jbang-launch/jpackage/*.rpm
            out/jreleaser/assemble/jbang-launch/jpackage/*.msi
